# Generated by Django 4.2.29 on 2026-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='cody',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
