# Generated by Django 4.2.29 on 2026-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_item_created_at_item_description_item_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
