# Generated by Django 4.2.29 on 2026-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_item_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cody',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
