# Generated by Django 4.2.29 on 2026-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cody_image_url_alter_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='outfits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
