# Generated by Django 4.2.29 on 2026-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_chatmessage_outfits'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='anchor_category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='anchor_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
